name: Semgrep Analysis

on:
  push:
  pull_request:
    branches:
      - main  # Adjust to your main branch name

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Semgrep Analysis
        uses: returntocorp/semgrep-action@v1
        with:
          config: .semgrep.yml

      - name: Archive Semgrep Results
        if: success()  # Only archive if Semgrep analysis succeeds
        run: |
          mkdir artifacts
          cp -r path/to/semgrep-results artifacts/
          tar czf semgrep-results.tar.gz artifacts/
        # You can adjust 'path/to/semgrep-results' to where Semgrep outputs results

      - name: Upload Semgrep Results Artifact
        if: success()  # Only upload artifact if Semgrep analysis succeeds
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-results
          path: semgrep-results.tar.gz

      # You can add more steps here for additional actions after Semgrep analysis

  # Add more jobs if needed for additional CI tasks





