
    
        name: Semgrep Analysis

on: [push, pull_request]

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: .semgrep.yml

  job:  # Correct indentation for this job definition
    container: returntocorp/ocaml:alpine-2024-01-18
    env:
      HOME: /root
    runs-on: ubuntu-latest
    steps:
      - name: Make checkout speedy
        run: git config --global fetch.parallel 50
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Configure git safedir properly
        run: git config --global --add safe.directory $(pwd)
      - env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
        name: Set GHA cache for OPAM in ~/.opam
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ runner.arch }}-opam-deps-4.14.0-${{hashFiles('semgrep.opam')}}
          path: ~/.opam
      - name: Install dependencies
        run: |
          eval $(opam env)
          make install-deps-ALPINE-for-semgrep-core
          make install-deps-for-semgrep-core
      - name: Build semgrep-core
        run: opam exec -- make core
      - name: Make artifact for bin/semgrep-core
        run: |
          mkdir artifacts
          cp bin/semgrep-core artifacts/
          tar czf artifacts.tgz artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: semgrep-core-x86-artifact
          path: artifacts.tgz
      - name: Test semgrep-core
        run: opam exec -- make core-test

    name: build-test-core-x86  # Correct indentation for job name
    on:
      workflow_call: null
      workflow_dispatch: null
