name: Semgrep Analysis

on:
  push:
    branches:
      - main  # Adjust as per your main branch name
  pull_request:
    branches:
      - main  # Adjust as per your main branch name

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          java-package: jdk
          architecture: x64

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: .semgrep.yml

      - name: Create artifacts
        run: |
          mkdir -p artifacts
          if [ -d "results/semgrep-results" ] && [ "$(ls -A results/semgrep-results)" ]; then
            cp -r results/semgrep-results/* artifacts/
            tar czf semgrep-results.tar.gz -C artifacts .
          else
            echo "Semgrep results directory not found or empty."
            ls -l results/semgrep-results  # Debugging: List contents of results/semgrep-results directory
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-results
          path: semgrep-results.tar.gz
