name: Semgrep and Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    name: Semgrep Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: .semgrep.yml

      - name: Create Semgrep Results Artifact
        run: |
          mkdir -p artifacts
          if [ -d "results/semgrep-results" ] && [ "$(ls -A results/semgrep-results)" ]; then
            cp -r results/semgrep-results/* artifacts/
            tar czf semgrep-results.tar.gz -C artifacts .
          else
            echo "Semgrep results directory not found or empty."
            ls -l results/semgrep-results  # Debugging: List contents of results/semgrep-results directory
            exit 1
          fi
        shell: bash

  maven:
    name: Maven Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Build and Test with Maven
        run: mvn clean verify --fail-never

      - name: Archive Maven Artifacts
        if: success() && github.event_name != 'pull_request'
        uses: actions/upload-artifact@v2
        with:
          name: maven-artifacts
          path: target/

      - name: Cleanup Semgrep Results
        if: success() && github.event_name != 'pull_request'
        run: rm -rf results/semgrep-results

