name: Semgrep Analysis

on:
  push:
  pull_request:
    branches:
      - main  # Adjust to your main branch name

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Semgrep Analysis
        uses: returntocorp/semgrep-action@v1
        with:
          config: .semgrep.yml

      - name: Prepare Semgrep Results
        run: |
          mkdir -p artifacts
          # Replace 'path/to/semgrep-results' with the actual path where Semgrep outputs results
          if [ -d "path/to/semgrep-results" ]; then
            cp -r path/to/semgrep-results/* artifacts/
          else
            echo "Semgrep results directory not found."
            exit 1
          fi
          tar czf semgrep-results.tar.gz artifacts/

      - name: Upload Semgrep Results Artifact
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-results
          path: semgrep-results.tar.gz

     



