name: Semgrep Analysis

on:
  push:
    branches:
      - main  # Trigger on push events to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Adjust Java version as per your project requirements

      - name: Build with Maven
        run: mvn clean verify --fail-never

      - name: Run Semgrep Analysis
        uses: returntocorp/semgrep-action@v1
        with:
          config: .semgrep.yml  # Specify the path to your Semgrep configuration file

      - name: Prepare Semgrep Results
        if: success()  # Only run if Semgrep analysis succeeds
        run: |
          mkdir -p artifacts
          if [ -d "results/semgrep-results" ] && [ "$(ls -A results/semgrep-results)" ]; then
            cp -r results/semgrep-results/* artifacts/
            tar czf semgrep-results.tar.gz -C artifacts .
          else
            echo "Semgrep results directory not found or empty."
            ls -l results/semgrep-results  # Debugging: List contents of results/semgrep-results directory
            exit 1
          fi

      - name: Upload Semgrep Results Artifact
        if: success()  # Upload artifact only if Semgrep analysis and preparation succeed
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-results
          path: semgrep-results.tar.gz

      # Add more steps as needed for testing, deployment, notifications, etc.

   
